### PR TITLE
Update to Play2-ReactiveMongo 0.11.0.play24

### PR DESCRIPTION
**Pull request by cchantep**

### CODE REVIEW

**Comment by cchantep** [comment]
Any feedback?

**Comment by wojciechk** [comment]
Cedric, thanks for your great contribution and update to play 2.4!
We will continue direction this and use DI all over the project as the next step.

**Comment by cchantep** [comment]
Do you plan to merge this first?

**Comment by cchantep** [comment]
Thanks @wojciechk and @MarcinBurczak

**Pull request merged**
